package com.myspace.gestcredito.implementacion;
import com.myspace.gestcredito.interfaz.ICalularCredito;
import com.myspace.gestcredito.modelo.datosCredito;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class calcularCreditoIM implements ICalularCredito {

    

	public void calularCredito(datosCredito auxx) {
	    
		int tol = 0;

		tol = ((((25 * (auxx.getSalario() - auxx.getGastosPerson()))) / 100) / auxx.getTiempoAmortiza());
		
		auxx.setTotalDeudas(tol);

    System.out.println("total endeudamiento " + tol);
	}




}