package com.myspace.gestcredito.interfaz;
import com.myspace.gestcredito.modelo.datosCredito;
/**
 * This class was automatically generated by the data modeler tool.
 */

public interface ICalularCredito {


    public void calularCredito(datosCredito auxx); 


}