package com.myspace.gestcredito.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosCredito implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("descripcion solicitud")
	private java.lang.String descripcionSolicitud;
	@org.kie.api.definition.type.Label("valor credito")
	private int valorCredito;
	@org.kie.api.definition.type.Label("tiempo amortizacion")
	private int tiempoAmortiza;
	@org.kie.api.definition.type.Label("salario")
	private int salario;
	@org.kie.api.definition.type.Label("gastos persona")
	private int gastosPerson;

	@org.kie.api.definition.type.Label(value = "total deudas")
	private int totalDeudas;

	public datosCredito() {
	}

	public java.lang.String getDescripcionSolicitud() {
		return this.descripcionSolicitud;
	}

	public void setDescripcionSolicitud(java.lang.String descripcionSolicitud) {
		this.descripcionSolicitud = descripcionSolicitud;
	}

	public int getValorCredito() {
		return this.valorCredito;
	}

	public void setValorCredito(int valorCredito) {
		this.valorCredito = valorCredito;
	}

	public int getTiempoAmortiza() {
		return this.tiempoAmortiza;
	}

	public void setTiempoAmortiza(int tiempoAmortiza) {
		this.tiempoAmortiza = tiempoAmortiza;
	}

	public int getSalario() {
		return this.salario;
	}

	public void setSalario(int salario) {
		this.salario = salario;
	}

	public int getGastosPerson() {
		return this.gastosPerson;
	}

	public void setGastosPerson(int gastosPerson) {
		this.gastosPerson = gastosPerson;
	}

	public int getTotalDeudas() {
		return this.totalDeudas;
	}

	public void setTotalDeudas(int totalDeudas) {
		this.totalDeudas = totalDeudas;
	}

	public datosCredito(java.lang.String descripcionSolicitud,
			int valorCredito, int tiempoAmortiza, int salario,
			int gastosPerson, int totalDeudas) {
		this.descripcionSolicitud = descripcionSolicitud;
		this.valorCredito = valorCredito;
		this.tiempoAmortiza = tiempoAmortiza;
		this.salario = salario;
		this.gastosPerson = gastosPerson;
		this.totalDeudas = totalDeudas;
	}

}